// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------------------- //
// wiznet_pio_spi_write_read //
// ------------------------- //

#define wiznet_pio_spi_write_read_wrap_target 0
#define wiznet_pio_spi_write_read_wrap 8

#define wiznet_pio_spi_write_read_offset_write_bits 0u
#define wiznet_pio_spi_write_read_offset_write_end 3u
#define wiznet_pio_spi_write_read_offset_read_end 9u

static const uint16_t wiznet_pio_spi_write_read_program_instructions[] = {
            //     .wrap_target
    0x6001, //  0: out    pins, 1         side 0     
    0x1040, //  1: jmp    x--, 0          side 1     
    0xe000, //  2: set    pins, 0         side 0     
    0xe080, //  3: set    pindirs, 0      side 0     
    0xf026, //  4: set    x, 6            side 1     
    0x4001, //  5: in     pins, 1         side 0     
    0x1045, //  6: jmp    x--, 5          side 1     
    0x4001, //  7: in     pins, 1         side 0     
    0x0084, //  8: jmp    y--, 4          side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program wiznet_pio_spi_write_read_program = {
    .instructions = wiznet_pio_spi_write_read_program_instructions,
    .length = 9,
    .origin = -1,
};

static inline pio_sm_config wiznet_pio_spi_write_read_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + wiznet_pio_spi_write_read_wrap_target, offset + wiznet_pio_spi_write_read_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

