name: Arduino-Pico Release Publisher

on:
  release:
    types: [published]

jobs:
  package:
    name: Update master JSON file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'          
#     - name: Cache PlatformIO
#       uses: actions/cache@v4
#       with:
#         path: ~/.platformio
#         key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
#     - name: Install PlatformIO
#       run: |
#         python -m pip install --upgrade pip
#         pip install --upgrade platformio
    - name: Deploy updated JSON
      env:
        BUILD_TYPE: package
        CI_GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
      run: |
           pip3 install PyGithub
           TAG=$(git describe --exact-match --tags)
           curl -L -o package_rp2040_index.json "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/$TAG/package_rp2040_index.json"
           ./package/update_release.py --token ${CI_GITHUB_API_KEY} --repo "$GITHUB_REPOSITORY" --tag global package_rp2040_index.json
           # Upload to Platform.IO
           # curl -LO $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/$TAG/rp2040-$TAG.zip
           # pio package publish rp2040-$TAG.zip --non-interactive
